# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: First Automation

on: 
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input Here'
        required: true

env:
  INSTANTCLIENT: instantclient-basic-linux.x64-21.9.0.0.0dbru

jobs:
  Test-Script-Python:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3 
      - run: sudo python -m pip install cx_Oracle --upgrade
      - run: sudo mkdir -p /opt/oracle  
      - run: wget -P /opt/oracle https://download.oracle.com/otn_software/linux/instantclient/219000/$INSTANTCLIENT.zip
      - run: sudo unzip /opt/oracle/$INSTANTCLIENT.zip
      - run: sudo apt-get install libaio1
      - run: echo "export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_9:$LD_LIBRARY_PATH" >> .bashrc 
      - run: . .bashrc

      - name: Accesso al repo
        uses: actions/checkout@v3
      - name: List Files
        run : ls ${{github.workspace}}
      - run: echo "Printing Data.txt"
      - run: cat ${{github.workspace}}/Data.txt 
      - run: |
          echo "Store: ${{ github.event.inputs.myInput }}"
          INPUT_MYINPUT=${{ github.event.inputs.myInput }} python3 main.py


        

    
