# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: First Automation

on: [push]

jobs:
  Test-Script-Python:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3 
      - name: Accesso al repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.branch}}
      - run: echo "Printing Data.txt"
      - run: cat ${{github.repository}}/Data.txt 
      - run: python3 ${{github.repository}}/main.py

    
