# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: First Automation

on: [push]

jobs:
  Test-Script-Python:
    runs-on: ubuntu-18.04
    steps:
      - run: apt-get install python3

      - run: echo "Printing Data.txt"
      - run: cat Data.txt 

      - run: python3 main.py

    
