# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: First Automation

on: [push]

jobs:
  Test-Script-Python:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3
      - run: cd ..
      - run: pwd
      - run: ls -la 
      - run: echo "Printing Data.txt"
      - run: cat Data.txt 

      - run: python3 main.py

    
